import { useState, useEffect } from "react";

//importing navbar
import Navbar from "../../Components/Navbar";
import AssessmentDashboard from "../../Components/Pages/Home/AssessmentDashboard";
import Sidebar from "../../Components/Sidebar";

import styles from "./style.module.css";

const Home = () => {

    const [windowSize, setWindowSize] = useState([
        window.innerWidth,
        window.innerHeight,
    ]);

    useEffect(() => {
        const handleWindowResize = () => {
            // if (window.innerWidth < 991) {
            //     setIsOpen(false);
            // }
            setWindowSize([window.innerWidth, window.innerHeight]);
        };

        window.addEventListener('resize', handleWindowResize);

        return () => {
            window.removeEventListener('resize', handleWindowResize);
        };
    });

    useEffect(() => {
        if (window.innerWidth < 991) {
            setIsOpen(false);
        }
    }, [windowSize]);

    const [hideExtra, setHideExtra] = useState<Number>(1);
    const [loading, setLoading] = useState<Boolean>(true);

    // For simple open/close sidebar
    const [isOpen, setIsOpen] = useState<Boolean>(true);

    // For minified sidebar
    const [isMinified, setIsMinified] = useState<Boolean>(false);

    const [currentMenuItem, setCurrentMenuItem] = useState<Number>(1);

    const [currentFullLengthItem, setCurrentFullLengthItem] = useState<Number>(1);

    return (
        <div className={`${styles.container} ${(isMinified) && (styles.minifySidebarContainer)}`}>
            {/* <Head>
            <title>Home - Project Management Software</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logocopy.ico" />
            </Head> 
        */}

            <main className={styles.main}>
                <Navbar
                    // For simple open/close sidebar
                    isOpen={isOpen}
                    setIsOpen={setIsOpen}
                    // For minified sidebar
                    isMinified={isMinified}
                    setIsMinified={setIsMinified}
                />
                <div className='d-flex'>
                    <Sidebar
                        currentMenuItem={currentMenuItem}
                        setCurrentMenuItem={setCurrentMenuItem}
                        // For simple open/close sidebar
                        isOpen={isOpen}
                        setIsOpen={setIsOpen}
                        // For minified sidebar
                        isMinified={isMinified}
                        setIsMinified={setIsMinified}
                    />

                    <div className={`${(isOpen) ? (styles.Home) : (styles.onSideClose)}`}>
                        <AssessmentDashboard
                            // For simple open/close sidebar
                            isOpen={isOpen}
                            setIsOpen={setIsOpen}
                            // For minified sidebar
                            isMinified={isMinified}
                            setIsMinified={setIsMinified}
                        />
                    </div>

                </div>
            </main>

            <footer className={styles.footer}>
                {/* 
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a> 
                */}
            </footer>
        </div>
    )
}
export default Home;